name: Deploy Service to Linux Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Target Linux Server / Environment'
        required: true
        type: choice
        options:
          - 'inventory-wms'
          - 'auth-wms'
          - 'development-server-01'
      application:
        description: 'Select Spring Boot Application to Deploy'
        required: true
        type: choice
        options:
          - 'inventory-management-app'
          - 'inventory-management-system'
          - 'auth-service'
      version:
        description: 'Target Application Version (Type concrete version or leave as "latest" to fetch most recent)'
        required: true
        type: choice
        options: 
          - 'Release_v1.0'
          - '1.0.0'
          - '1.0.1'
      properties:
        description: 'Select Spring Boot Application to Deploy'
        required: true
        type: choice
        options:
          - 'authentication-properties'
          - 'inventory-management-properties'
          
      propertiesVersion:
        description: 'Target Application Properties Version (Type concrete version or leave as "latest" to fetch most recent)'
        required: true
        type: choice
        options: 
          - 'Release_v1.0'
          - '1.0.0'
          - '1.0.1'    

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        # 1. Set up JDK SECOND
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          
        # 2. Delete the file
      - name: Remove existing settings.xml
        run: rm -f $HOME/.m2/settings.xml

        # 3. Setup Maven settings FIRST
      - name: Setup Maven settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          override: true
          servers: |
            [{"id":"github","username":"${{ secrets.USERNAME }}","password":"${{ secrets.GITHUB_TOKEN }}"}]
          repositories: |
            [
             {"id":"github","name":"${{ github.event.inputs.application }}","url":"https://maven.pkg.github.com/rsp777/${{ github.event.inputs.application }}"},
             {"id":"github","name":"${{ github.event.inputs.properties }}","url":"https://maven.pkg.github.com/rsp777/${{ github.event.inputs.properties }}"}]    

      # 3. Handle Mapping & Fetching Remote Versions
      - name: Set Environment Variables & Resolve Version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo https://maven.pkg.github.com/rsp777/${{ github.event.inputs.application }}
          if [ "${{ github.event.inputs.environment }}" = "inventory-wms" ]; then
            echo "SERVER_HOST=${{ secrets.INVENTORY_WMS_SERVER_ID }}" >> $GITHUB_ENV
            {
              echo "SERVER_SSH_KEY<<EOF"
              echo "${{ secrets.INVENTORY_WMS_SSH_KEY }}"
              echo "EOF"
            } >> $GITHUB_ENV
            {
              echo "SERVER_SSH_PASSPHRASE<<EOF"
              echo "${{ secrets.INVENTORY_WMS_SSH_PASSPHRASE }}"
              echo "EOF"
            } >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "auth-wms" ]; then
            echo "SERVER_HOST=${{ secrets.AUTH_WMS_SERVER_IP }}" >> $GITHUB_ENV
            {
              echo "SERVER_SSH_KEY<<EOF"
              echo "${{ secrets.AUTH_WMS_SSH_KEY }}"
              echo "EOF"
            } >> $GITHUB_ENV
            {
              echo "SERVER_SSH_PASSPHRASE<<EOF"
              echo "${{ secrets.AUTH_WMS_SSH_PASSPHRASE }}"
              echo "EOF"
            } >> $GITHUB_ENV
          else
            echo "Server Not Configured"
          fi
          
          APP_NAME="${{ github.event.inputs.application }}"
          INPUT_VERSION="${{ github.event.inputs.version }}"
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV


          case "$APP_NAME" in
            "inventory-management-app")
              GROUP_ID="com.pawar.inventory.app"
              PACKAGE_NAME="com.pawar.inventory.app.inventory-management-app"
              ;;
            "inventory-management-system")
              GROUP_ID="com.pawar.inventory"
              ;;
            "auth-service")
              GROUP_ID="com.pawar.auth"
              ;;
            *)
              echo "Unknown application: $APP_NAME"
              exit 1
              ;;
          esac

          echo "GROUP_ID=${GROUP_ID}" >> $GITHUB_ENV
          
          if [ "$INPUT_VERSION" = "latest" ]; then
            echo "Fetching the latest package version via GitHub Packages API..."
            PACKAGE_VERSION=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://maven.pkg.github.com/rsp777/$GROUP_ID.$APP_NAME/versions" \
              | jq -r '..name // "1.0.0-SNAPSHOT"')
              
            echo "Resolved latest version: $PACKAGE_VERSION"
            echo "APP_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          else
            echo "Using manual input version: $INPUT_VERSION"
            echo "APP_VERSION=$INPUT_VERSION" >> $GITHUB_ENV
          fi

          # Set Properties and Properties Version
          PROPERTIES_NAME="${{ github.event.inputs.properties }}"
          PROPERTIES_VERSION="${{ github.event.inputs.propertiesVersion }}"
          echo "PROPERTIES_NAME=${PROPERTIES_NAME}" >> $GITHUB_ENV
          echo "PROPERTIES_VERSION=${PROPERTIES_VERSION}" >> $GITHUB_ENV

          case "$PROPERTIES_NAME" in
            "authentication-properties")
              PROP_GROUP_ID="com.pawar.auth"
              ;;
            "inventory-management-properties")
              PROP_GROUP_ID="com.pawar.inventory"
              ;;
            *)
              echo "Unknown application: $APP_NAME"
              exit 1
              ;;
          esac
          echo "PROP_GROUP_ID=${PROP_GROUP_ID}" >> $GITHUB_ENV
      # 3. Download Properties JAR from GitHub Package Registry
      - name: Download Properties JAR from Maven Registry
        run: |
          mkdir -p target
          # Uses explicit settings routing file flag (-s) just like your working setup
          mvn dependency:copy  \
          -Dartifact=${{env.PROP_GROUP_ID}}:${{ env.PROPERTIES_NAME }}:${{ env.PROPERTIES_VERSION }}:jar \
          -Dtransitive=false \
          -DoutputDirectory=$HOME/.m2/repository \
          -s $HOME/.m2/settings.xml

          # Copy from Maven cache to target directory
          cp $HOME/.m2/repository/$(echo ${{ env.PROP_GROUP_ID }} | tr '.' '/')//${{ env.PROPERTIES_NAME }}/${{ env.PROPERTIES_VERSION }}/${{ env.PROPERTIES_NAME }}-${{ env.PROPERTIES_VERSION }}.jar ./target/${{ env.PROPERTIES_NAME }}.jar
          echo "=== Target directory contents ==="
          
          ls -ltr target/
    
          echo "=== Checking for JAR files ==="
          find target -name "*.jar" -o -name "*.pom"
    
            if [ ! -f target/${{ env.PROPERTIES_NAME }}.jar ]; then
              echo "Error: Artifact download failed"
              exit 1
            fi

      # 4. Download Target JAR from GitHub Package Registry
      - name: Download Application Artifact from Maven Registry
        run: |
          mkdir -p target
          # Uses explicit settings routing file flag (-s) just like your working setup
          mvn dependency:copy  \
          -Dartifact=${{env.GROUP_ID}}:${{ env.APP_NAME }}:${{ env.APP_VERSION }}:jar \
          -Dtransitive=false \
          -DoutputDirectory=$HOME/.m2/repository \
          -s $HOME/.m2/settings.xml

          # Copy from Maven cache to target directory
          cp $HOME/.m2/repository/$(echo ${{ env.GROUP_ID }} | tr '.' '/')//${{ env.APP_NAME }}/${{ env.APP_VERSION }}/${{ env.APP_NAME }}-${{ env.APP_VERSION }}.jar ./target/${{ env.APP_NAME }}.jar
          echo "=== Target directory contents ==="
          
          ls -ltr target/
    
          echo "=== Checking for JAR files ==="
          find target -name "*.jar" -o -name "*.pom"
    
            if [ ! -f target/${{ env.APP_NAME }}.jar ]; then
              echo "Error: Artifact download failed"
              exit 1
            fi
        
      # 5. Connect runner container as a temporary secure Tailscale network node
      - name: Connect to Tailscale Network
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:sop
      
      # 6. Copy Properties JAR to Linux Server via SCP
      - name: Copy Properties JAR to Linux Server via SCP
        uses: appleboy/scp-action@master
        
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          passphrase: ${{ env.SERVER_SSH_PASSPHRASE }}
          port: 22
          source: "target/${{ env.PROPERTIES_NAME }}.jar"
          target: "/tmp"
          strip_components: 1

      # 7. Copy Application JAR to Linux Server via SCP
      - name: Copy Application JAR to Linux Server via SCP
        uses: appleboy/scp-action@master
        
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          passphrase: ${{ env.SERVER_SSH_PASSPHRASE }}
          port: 22
          source: "target/${{ env.APP_NAME }}.jar"
          target: "/tmp"
          strip_components: 1

      # 8. Deploy the Properties Artifact to Remote Linux Server
      - name: Deploy the Properties Artifact to Remote Linux Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          passphrase: ${{ env.SERVER_SSH_PASSPHRASE }}
          port: 22
          script: |
            echo "Deploying ${{ env.PROPERTIES_NAME }}:${{ env.PROPERTIES_VERSION }} to ${{ env.SERVER_HOST }}"                        
            mv /tmp/${{ env.PROPERTIES_NAME }}.jar ~/apps/${{ github.event.inputs.environment }}/properties/${{ env.PROPERTIES_NAME }}.jar
            rm -f /tmp/${{ env.PROPERTIES_NAME }}.jar
            echo "=== Checking deployed properties for JAR files ==="
    
            if [ ! -f ~/apps/${{ github.event.inputs.environment }}/properties/${{ env.PROPERTIES_NAME }}.jar ]; then
              echo "Error: Properties Artifact ${{ env.PROPERTIES_NAME }} download failed"
              exit 1
            fi
            chmod +x ~/apps/${{ github.event.inputs.environment }}/properties/${{ env.PROPERTIES_NAME }}.jar
            echo "Extracting properties: ${{ env.PROPERTIES_NAME }}"
            cd  ~/apps/${{ github.event.inputs.environment }}/properties/
            $JAVA_HOME/jar -xf ${{ env.PROPERTIES_NAME }}.jar ${{ env.APP_NAME }}
            echo "=== Checking extracted properties for JAR files ==="
            pwd
            ls -ltr
            find auth-service -name "auth-service" -o -name "*.properties" -o -name "*.xml"
    
            if ! find ${{ env.APP_NAME }} -name "*.properties" -type f | grep -q .; then
                echo "Error: No properties files found"
                exit 1
            fi
           
            
            echo "Deployed Properties: ${{ env.PROPERTIES_NAME }}"

      # 9. Deploy the Application Artifact to Remote Linux Server
      - name: Deploy the Application Artifact to Remote Linux Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          passphrase: ${{ env.SERVER_SSH_PASSPHRASE }}
          port: 22
          script: |
            echo "Deploying ${{ env.APP_NAME }}:${{ env.APP_VERSION }} to ${{ env.SERVER_HOST }}"                        
            mv /tmp/${{ env.APP_NAME }}.jar ~/apps/${{ github.event.inputs.environment }}/artifacts/${{ env.APP_NAME }}.jar
            rm -f /tmp/${{ env.APP_NAME }}.jar

            chmod +x ~/apps/${{ github.event.inputs.environment }}/artifacts/${{ env.APP_NAME }}.jar
            echo "Restarting service: ${{ env.APP_NAME }}"
            chmod +x ~/apps/${{ github.event.inputs.environment }}/scripts/stop.sh ~/apps/${{ github.event.inputs.environment }}/scripts/start.sh
            ~/apps/${{ github.event.inputs.environment }}/scripts/stop.sh ${{ env.APP_NAME }}
            ~/apps/${{ github.event.inputs.environment }}/scripts/start.sh ${{ env.APP_NAME }}
            echo "Restarted service: ${{ env.APP_NAME }}"
